export interface AttackData {
  toHit: number;
  damageRoll: string;
  info?: string;
}

export interface CharacterSheetData {
  readonly name: string;
  readonly proficiencyBonus: number;
  readonly checkBonuses: Map<string, number>;
  readonly saveBonuses: Map<string, number>;
  readonly abilityBonuses: Map<string, number>;
  readonly attackBonuses: Map<string, AttackData>;
}

export interface Spell {
  name: string;
  desc: string;
  page: string;
  range: string;
  components: string;
  material?: string;
  ritual: string;
  duration: string;
  concentration: string;
  castingTime: string;
  level: string;
  school: string;
  class: string;
  higherLevel?: string;
  archetype?: string;
  domains?: string;
  patrons?: string;
  circles?: string;
  oaths?: string;
}

export const SKILL_ORDER = [
  'Acrobatics',
  'Animal Handling',
  'Arcana',
  'Athletics',
  'Deception',
  'History',
  'Insight',
  'Intimidation',
  'Investigation',
  'Medicine',
  'Nature',
  'Perception',
  'Performance',
  'Persuasion',
  'Religion',
  'Sleight of Hand',
  'Stealth',
  'Survival',
];

export const ABILITY_ORDER = [
  'Strength',
  'Dexterity',
  'Constitution',
  'Intelligence',
  'Wisdom',
  'Charisma',
];

export const LOOKUP_ORDER = [
  "Abi-Dalzim's Horrid Wilting",
  'Absorb Elements',
  'Acid Splash',
  "Aganazzar's Scorcher",
  'Aid',
  'Alarm',
  'Alter Self',
  'Animal Friendship',
  'Animal Messenger',
  'Animal Shapes',
  'Animate Dead',
  'Animate Objects',
  'Antilife Shell',
  'Antimagic Field',
  'Antipathy/Sympathy',
  'Arcane Eye',
  'Arcane Gate',
  'Arcane Lock',
  'Armor of Agathys',
  'Arms of Hadar',
  'Astral Projection',
  'Augury',
  'Aura of Life',
  'Aura of Purity',
  'Aura of Vitality',
  'Awaken',
  'Bane',
  'Banishing Smite',
  'Banishment',
  'Barkskin',
  'Beacon of Hope',
  'Beast Bond',
  'Beast Sense',
  'Bestow Curse',
  "Bigby's Hand",
  'Blade Barrier',
  'Blade Ward',
  'Bless',
  'Blight',
  'Blinding Smite',
  'Blindness/Deafness',
  'Blink',
  'Blur',
  'Bones of the Earth',
  'Booming Blade',
  'Branding Smite',
  'Burning Hands',
  'Call Lightning',
  'Calm Emotions',
  'Catapult',
  'Chain Lightning',
  'Charm Person',
  'Chill Touch',
  'Chromatic Orb',
  'Circle of Death',
  'Circle of Power',
  'Clairvoyance',
  'Clone',
  'Cloud of Daggers',
  'Cloudkill',
  'Color Spray',
  'Command',
  'Commune',
  'Commune with Nature',
  'Compelled Duel',
  'Comprehend Languages',
  'Compulsion',
  'Cone of Cold',
  'Confusion',
  'Conjure Animals',
  'Conjure Barrage',
  'Conjure Celestial',
  'Conjure Elemental',
  'Conjure Fey',
  'Conjure Minor Elementals',
  'Conjure Volley',
  'Conjure Woodland Beings',
  'Contact Other Plane',
  'Contagion',
  'Contingency',
  'Continual Flame',
  'Control Flames',
  'Control Water',
  'Control Weather',
  'Control Winds',
  'Cordon of Arrows',
  'Counterspell',
  'Create Bonfire',
  'Create Food and Water',
  'Create or Destroy Water',
  'Create Undead',
  'Creation',
  'Crown of Madness',
  "Crusader's Mantle",
  'Cure Wounds',
  'Dancing Lights',
  'Darkness',
  'Darkvision',
  'Daylight',
  'Death Ward',
  'Delayed Blast Fireball',
  'Demiplane',
  'Destructive Wave',
  'Detect Evil and Good',
  'Detect Magic',
  'Detect Poison and Disease',
  'Detect Thoughts',
  'Dimension Door',
  'Disguise Self',
  'Disintegrate',
  'Dispel Evil and Good',
  'Dispel Magic',
  'Dissonant Whispers',
  'Divination',
  'Divine Favor',
  'Divine Word',
  'Dominate Beast',
  "Drawmij's Instant Summons",
  'Dominate Monster',
  'Dominate Person',
  'Dream',
  'Druidcraft',
  'Dust Devil',
  'Earth Tremor',
  'Earthbind',
  'Earthquake',
  'Eldritch Blast',
  'Elemental Bane',
  'Elemental Weapon',
  'Enhance Ability',
  'Enlarge/Reduce',
  'Ensnaring Strike',
  'Entangle',
  'Enthrall',
  'Erupting Earth',
  'Etherealness',
  "Evard's Black Tentacles",
  'Expeditious Retreat',
  'Eyebite',
  'Fabricate',
  'Faerie Fire',
  'False Life',
  'Fear',
  'Feather Fall',
  'Feeblemind',
  'Feign Death',
  'Find Familiar',
  'Find Steed',
  'Find the Path',
  'Find Traps',
  'Finger of Death',
  'Fireball',
  'Fire Bolt',
  'Fire Shield',
  'Fire Storm',
  'Flame Arrows',
  'Flame Blade',
  'Flame Strike',
  'Flaming Sphere',
  'Flesh to Stone',
  'Fly',
  'Fog Cloud',
  'Forbiddance',
  'Forcecage',
  'Foresight',
  'Freedom of Movement',
  'Friends',
  'Frostbite',
  'Gaseous Form',
  'Gate',
  'Geas',
  'Gentle Repose',
  'Giant Insect',
  'Glibness',
  'Globe of Invulnerability',
  'Glyph of Warding',
  'Goodberry',
  'Grasping Vine',
  'Grease',
  'Greater Invisibility',
  'Greater Restoration',
  'Green-Flame Blade',
  'Guardian of Faith',
  'Guards and Wards',
  'Guidance',
  'Guiding Bolt',
  'Gust',
  'Gust of Wind',
  'Hail of Thorns',
  'Hallow',
  'Hallucinatory Terrain',
  'Harm',
  'Haste',
  'Heal',
  'Healing Word',
  'Heat Metal',
  'Hellish Rebuke',
  "Heroes' Feast",
  'Heroism',
  'Hex',
  'Hold Monster',
  'Hold Person',
  'Holy Aura',
  'Hunger of Hadar',
  "Hunter's Mark",
  'Hypnotic Pattern',
  'Ice Knife',
  'Ice Storm',
  'Identify',
  'Illusory Script',
  'Immolation',
  'Imprisonment',
  'Incendiary Cloud',
  'Inflict Wounds',
  'Insect Plague',
  'Investiture of Flame',
  'Investiture of Ice',
  'Investiture of Stone',
  'Investiture of Wind',
  'Invisibility',
  'Jump',
  'Knock',
  'Legend Lore',
  "Leomund's Secret Chest",
  "Leomund's Tiny Hut",
  'Lesser Restoration',
  'Levitate',
  'Light',
  'Lightning Arrow',
  'Lightning Bolt',
  'Lightning Lure',
  'Locate Animals or Plants',
  'Locate Creature',
  'Locate Object',
  'Longstrider',
  'Maelstrom',
  'Mage Armor',
  'Mage Hand',
  'Magic Circle',
  'Magic Jar',
  'Magic Missile',
  'Magic Mouth',
  'Magic Stone',
  'Magic Weapon',
  'Major Image',
  'Mass Cure Wounds',
  'Mass Heal',
  'Mass Healing Word',
  'Mass Suggestion',
  "Maximilian's Earthen Grasp",
  'Maze',
  'Meld into Stone',
  "Melf's Acid Arrow",
  "Melf's Minute Meteors",
  'Mending',
  'Message',
  'Meteor Swarm',
  'Mind Blank',
  'Minor Illusion',
  'Mirage Arcane',
  'Mirror Image',
  'Mislead',
  'Misty Step',
  'Modify Memory',
  'Mold Earth',
  'Moonbeam',
  "Mordenkainen's Faithful Hound",
  "Mordenkainen's Magnificent Mansion",
  "Mordenkainen's Private Sanctum",
  "Mordenkainen's Sword",
  'Move Earth',
  'Nondetection',
  "Nystul's Magic Aura",
  "Otiluke's Freezing Sphere",
  "Otiluke's Resilient Sphere",
  "Otto's Irresistible Dance",
  'Pass without Trace',
  'Passwall',
  'Permanent Image',
  'Phantasmal Force',
  'Phantasmal Killer',
  'Phantom Steed',
  'Planar Ally',
  'Planar Binding',
  'Plane Shift',
  'Plant Growth',
  'Poison Spray',
  'Polymorph',
  'Power Word Heal',
  'Power Word Kill',
  'Power Word Stun',
  'Prayer of Healing',
  'Prestidigitation',
  'Primordial Ward',
  'Prismatic Spray',
  'Prismatic Wall',
  'Produce Flame',
  'Programmed Illusion',
  'Project Image',
  'Protection from Energy',
  'Protection from Evil and Good',
  'Protection from Poison',
  'Purify Food and Drink',
  'Pyrotechnics',
  'Raise Dead',
  "Rary's Telepathic Bond",
  'Ray of Enfeeblement',
  'Ray of Frost',
  'Ray of Sickness',
  'Regenerate',
  'Reincarnate',
  'Remove Curse',
  'Resistance',
  'Resurrection',
  'Reverse Gravity',
  'Revivify',
  'Rope Trick',
  'Sacred Flame',
  'Sanctuary',
  'Scorching Ray',
  'Scrying',
  'Searing Smite',
  'See Invisibility',
  'Seeming',
  'Sending',
  'Sequester',
  'Shape Water',
  'Shapechange',
  'Shatter',
  'Shield',
  'Shield of Faith',
  'Shillelagh',
  'Shocking Grasp',
  'Silence',
  'Silent Image',
  'Simulacrum',
  'Skywrite',
  'Sleep',
  'Sleet Storm',
  'Slow',
  "Snilloc's Snowball Swarm",
  'Spare the Dying',
  'Speak with Animals',
  'Speak with Dead',
  'Speak with Plants',
  'Spider Climb',
  'Spike Growth',
  'Spirit Guardians',
  'Spiritual Weapon',
  'Staggering Smite',
  'Stinking Cloud',
  'Stone Shape',
  'Stoneskin',
  'Storm of Vengeance',
  'Storm Sphere',
  'Suggestion',
  'Sunbeam',
  'Sunburst',
  'Swift Quiver',
  'Sword Burst',
  'Symbol',
  "Tasha's Hideous Laughter",
  'Telekinesis',
  'Telepathy',
  'Teleport',
  'Teleportation Circle',
  "Tenser's Floating Disk",
  'Thaumaturgy',
  'Thorn Whip',
  'Thunderous Smite',
  'Thunderclap',
  'Thunderwave',
  'Tidal Wave',
  'Time Stop',
  'Tongues',
  'Transmute Rock',
  'Transport via Plants',
  'Trap the Soul',
  'Tree Stride',
  'True Polymorph',
  'True Resurrection',
  'True Seeing',
  'True Strike',
  'Tsunami',
  'Unseen Servant',
  'Vampiric Touch',
  'Vicious Mockery',
  'Vitriolic Sphere',
  'Wall of Fire',
  'Wall of Force',
  'Wall of Ice',
  'Wall of Sand',
  'Wall of Stone',
  'Wall of Thorns',
  'Wall of Water',
  'Warding Bond',
  'Warding Wind',
  'Water Breathing',
  'Water Walk',
  'Watery Sphere',
  'Web',
  'Weird',
  'Whirlwind',
  'Wind Walk',
  'Wind Wall',
  'Wish',
  'Witch Bolt',
  'Word of Recall',
  'Wrathful Smite',
  'Zone of Truth',
];

export const ADVANTAGE = 'advantage';
export const DISADVANTAGE = 'disadvantage';
