name: Client Test CI 

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - name: tsc compile
      uses: iCrawl/action-tsc@v1 
    - run: npm run test
      working-directory: app/static
