name: Client Test CI 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      working-directory: app/static
    - name: tsc compile
      uses: iCrawl/action-tsc@v1 
    - run: npm run test
      working-directory: app/static
