name: DnD Testing

on:
  push: 
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
      working-directory: app/static
    - run: npm run test
      working-directory: app/static
